feat: save aluno
ludgerobezerra/NossaBiblioteca pull request #2
Opened 2022-03-29 23:47 UTC by ludgerobezerra

2022-03-30 00:35 UTC, ejrgeek requested changes

2022-03-30 00:35 UTC, ejrgeek commented on src/main/java/br/edu/catolica/ppi/nossaBiblioteca/service/AlunoService.java
> +        return alunoRepository.save(aluno);
Não precisa achar o aluno antes de dar um 'save' para atualizar?

2022-03-30 00:35 UTC, ejrgeek commented on src/main/java/br/edu/catolica/ppi/nossaBiblioteca/repository/AlunoRepository.java
> +
Está sendo implementado algo aqui?

2022-04-01 21:51 UTC, ludgerobezerra commented on src/main/java/br/edu/catolica/ppi/nossaBiblioteca/service/AlunoService.java
> +        return alunoRepository.save(aluno);
Nesse caso para que o aluno seja atualizado preciso passar o Id, que sera uma consula que sera feita ainda.

2022-04-01 21:52 UTC, ludgerobezerra commented on src/main/java/br/edu/catolica/ppi/nossaBiblioteca/repository/AlunoRepository.java
> +
Ai esta o repositorio DAO que será implementado na classe AlunoService.

2022-04-01 23:12 UTC, ejrgeek approved these changes

2022-04-01 23:12 UTC, merged